ALGOSPAM/Problems

봉봉/README.md, 봉봉/Solution.cs
=> 봉봉 / 문자열 내 마음대로 정렬하기

taeheelee/README.md
1. 연습문제 - 문자열 내 마음대로 정렬하기
2. 스택/큐 - 기능개발
=> #알고리즘풀이 1차, 20210523, 이태희

Foo/README.md
시간 복잡도에 대해서 조금 더 공부해야 할듯 하지만. 통과 하는 코드입니다.
- 문자열 내 마음대로 정렬하기 결과
- 기능개발 결과
=> 0523 문자열 내 마음대로 정렬하기, 기능 개발 풀이 

뻥튀기/README.md
5월 23일 - 문자열 내마음대로 정렬하기 (Javascript)
=> 뻥튀기/문자열 내마음대로 정렬하기 (Javascript)

괴/README.md
알고리즘 - 스킬 트리 풀이
https://programmers.co.kr/learn/courses/30/lessons/49993
=> [괴] 2021-05-23 알고리즘 풀이 : 49993

leetaehee/README.md
=> 2주차 문제풀이 - 스킬트리 & 게임 맵 최단거리

leetaehee/README.md
언어 : 자바
프로그래머스 - 멀리뛰기(난이도 3), 오픈채팅방(난이도 2)
=> 3주차 문제풀이 - 멀리뛰기, 오픈채팅방

괴/README.md
알고리즘 - 오픈채팅방
https://programmers.co.kr/learn/courses/30/lessons/42888
=> [괴] 2021-06-06 알고리즘 풀이 : 42888

Foo/README.md
https://soobarkbar.tistory.com/61
참고 레퍼런스입니다.
=> 21.06.12 네트워크, Sum of Unique Elements

안녕하세요/README.md
=> 안녕하세요-네트워크, Sum of Unique Elements

괴/README.md
[괴] 2021-06-20 알고리즘 풀이 
Minimum Add to Make Parentheses Valid => Accepted
Container With Most Water => Time Limit Exceeded
=> [괴] 2021-06-20 알고리즘 풀이 : Minimum Add to Make Parentheses Valid

Foo/README.md
https://leetcode.com/submissions/detail/510221399/
https://leetcode.com/submissions/detail/510601828/
=> 21.06.20 푸/minimum-add-to-make-parentheses-valid, Container With Most Water

leetaehee/README.md
=> 5주차 문제풀이 - 리트코드

안녕하세요/README.md
AVL문제는 input값을 이해를 못했습니다.
다음에 다시 풀어보겠습니다.
=> 안녕하세요 - 조이스틱

괴/README.md
1. Tree 의 이론적 배경 및 구조 학습
2. 알고리즘 - Subtree of Another Tree
https://leetcode.com/problems/subtree-of-another-tree/
=> [괴] 2021-07-25 알고리즘 풀이 : Subtree of Another Tree

괴/README.md
알고리즘 - Longest Substring Without Repeating Characters
https://leetcode.com/problems/longest-substring-without-repeating-characters/
=> [괴] 2021-08-01 알고리즘 풀이 : Longest Substring Without Repeating Characters

Foo/README.md
=> 21.08.01 Longest Substring Without Repeating Characters, Unique Paths

괴/README.md
알고리즘 - N으로 표현
https://programmers.co.kr/learn/courses/30/lessons/42895
=> [괴] 2021-08-08 알고리즘 풀이 : N으로 표현

괴/README.md
https://leetcode.com/problems/climbing-stairs/
https://programmers.co.kr/learn/courses/30/lessons/42840
=> [괴] 2021-08-15 알고리즘 풀이 : Climbing Stairs / 모의고사

README.md, 초롱/README.md
=> 초롱_1. Two Sum

괴/README.md
19. Remove Nth Node From End of List
https://leetcode.com/problems/remove-nth-node-from-end-of-list/
1957. Delete Characters to Make Fancy String
https://leetcode.com/problems/delete-characters-to-make-fancy-string/
=> [괴] 2021-08-29 알고리즘 풀이 : Remove Nth Node From End of List / Delete Characters to Make Fancy String

Foo/README.md
https://leetcode.com/problems/search-in-rotated-sorted-array/
https://leetcode.com/problems/3sum/
=> 푸 / search in rotated sorted array , 3sum

README.md, 초롱/README.md
=> 33. Search in Rotated Sorted Array (순환된 정렬 배열의 검색)

Foo/README.md
https://leetcode.com/problems/jump-game-ii/description/
https://programmers.co.kr/learn/courses/30/lessons/42842
=> 푸 / 카펫, Jump Game 2

README.md, 초롱/README.md
=> Update and rename README.md to 초롱/README.md

괴/README.md
56. Merge Intervals
- https://leetcode.com/problems/merge-intervals/
=> [괴] 2021-11-07 알고리즘 풀이 : Merge Intervals

괴/README.md
[괴] 2021-11-14 알고리즘 풀이
- 412. Fizz Buzz
- 1791. Find Center of Star Graph (선택)
=> [괴] 2021-11-14 알고리즘 풀이 : Fizz Buzz / Find Center of Star Graph (선택)

bokdung/README.md
=> Generate Parentheses

괴/README.md
https://programmers.co.kr/learn/courses/30/lessons/81301
https://programmers.co.kr/learn/courses/30/lessons/77484
=> [괴] 2022-02-06 : 숫자 문자열과 영단어 / 로또의 최고 순위와 최저 순위

괴/README.md
https://leetcode.com/problems/merge-nodes-in-between-zeros/
https://leetcode.com/problems/multiply-strings/
=> [괴] 2022-03-13 : Merge Nodes in Between Zeros / Multiply Strings

괴/README.md
https://leetcode.com/problems/remove-all-occurrences-of-a-substring/
=> [괴] 2022-03-20 : Remove All Occurrences of a Substring

Foo/README.md
https://leetcode.com/problems/sudoku-solver/
=> Foo/ Sudoku Solver

괴/README.md
https://leetcode.com/problems/shuffle-string/
https://leetcode.com/problems/find-center-of-star-graph/
=> [괴] 2022.04.03 : Shuffle String / Find Center of Star Graph

BBADDA/README.md
1. 행렬의 덧셈 (LV1)
2. x만큼 간격이 있는 n개의 숫자 (LV1)
=> 2022-04-03 원하는 문제 2개

Foo/README.md
https://programmers.co.kr/learn/courses/30/lessons/60057
=> 푸 / 문자열 압축하기

BBADDA/README.md
1. 프로그래머스 - 시저 암호 (LV1)
2. 프로그래머스 - 핸드폰 번호 가리기 (LV1)
=> 문자열 관련 문제 2개

.gitignore, BBADDA/README.md
=> 그래프 및 노드 문제 1개

README.md, 초롱/README.md
https://leetcode.com/problems/delete-node-in-a-bst/
=> 초롱: 노드관련 문제 풀이 450. Delete Node in a BST (java풀이)

koook/readme.md, readme/문자열다루기기본, readme/문자열을정수로바꾸기
=> 2022.05.22 kooook

괴/README.md
로또의 최고 순위와 최저 순위
https://school.programmers.co.kr/learn/courses/30/lessons/77484
2299. Strong Password Checker II
https://leetcode.com/problems/strong-password-checker-ii/
=> [괴] 2022.08.07 : 로또의 최고 순위와 최저 순위 / Strong Password Checker II

README.md, 초롱/README.md
=> 2299. Strong Password Checker II 초롱 풀이

괴/README.md
1910. Remove All Occurrences of a Substring
https://leetcode.com/problems/remove-all-occurrences-of-a-substring/
2284. Sender With Largest Word Count
https://leetcode.com/problems/sender-with-largest-word-count/
=> [괴] 2022.08.14 : Remove All Occurrences of a Substring -> Sender With Largest Word Count 

README.md, 초롱/README.md
=> 1302. Deepest Leaves Sum

삼다수/README.md
=> 안전지대_삼다수 README.md

Foo/README.md
=> 23.03.04 Foo Deepest Leaves Sum / 안전지대

Foo/README.md
https://blog.uniony.me/cpp/next_permutation/
=> 23.04.02/ 푸 / Binary Tree Pruning, Shuffle an Array
